# Generated by Django 5.2.4 on 2025-08-01 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoBiomedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('serie', models.CharField(help_text='Número de serie único para cada equipo', max_length=255, unique=True)),
                ('codigo_interno', models.CharField(blank=True, help_text='Placa o código de identificación interno', max_length=100, null=True)),
                ('foto_equipo', models.ImageField(blank=True, null=True, upload_to='fotos_equipos/')),
                ('clasificacion_riesgo', models.CharField(choices=[('I', 'Clase I'), ('IIA', 'Clase IIa'), ('IIB', 'Clase IIb'), ('III', 'Clase III')], default='I', max_length=10)),
                ('registro_sanitario', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(help_text='Servicio o área donde se encuentra el equipo', max_length=255)),
                ('fecha_adquisicion', models.DateField()),
                ('forma_adquisicion', models.CharField(choices=[('COMPRA', 'Compra'), ('DONACION', 'Donación'), ('COMODATO', 'Comodato'), ('OTRO', 'Otro')], default='COMPRA', max_length=50)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('factura', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('garantia_anios', models.PositiveIntegerField(default=1)),
                ('vida_util_anios', models.PositiveIntegerField(default=10)),
                ('voltaje', models.DecimalField(blank=True, decimal_places=2, help_text='Voltaje (V)', max_digits=7, null=True)),
                ('corriente', models.DecimalField(blank=True, decimal_places=2, help_text='Corriente (A)', max_digits=7, null=True)),
                ('potencia', models.DecimalField(blank=True, decimal_places=2, help_text='Potencia (W)', max_digits=7, null=True)),
                ('frecuencia', models.DecimalField(blank=True, decimal_places=2, help_text='Frecuencia (Hz)', max_digits=7, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura (°C)', max_digits=5, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso (Kg)', max_digits=7, null=True)),
                ('tecnologia_predominante', models.CharField(blank=True, choices=[('MECANICO', 'Mecánico'), ('ELECTRICO', 'Eléctrico'), ('ELECTRONICO', 'Electrónico'), ('HIDRAULICO', 'Hidráulico'), ('NEUMATICO', 'Neumático'), ('INFORMATICO', 'Informático')], max_length=50, null=True)),
                ('otros_datos_tecnicos', models.TextField(blank=True, null=True)),
                ('frecuencia_mantenimiento_meses', models.PositiveIntegerField(default=6)),
                ('requiere_calibracion', models.BooleanField(default=False)),
                ('frecuencia_calibracion_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('estado_actual', models.CharField(choices=[('FUNCIONAL', 'En Funcionamiento'), ('FUERA_DE_SERVICIO', 'Fuera de Servicio'), ('EN_REPARACION', 'En Reparación (A la espera de repuesto)'), ('DADO_DE_BAJA', 'Dado de Baja')], default='FUNCIONAL', max_length=50)),
                ('tiene_manual_usuario', models.BooleanField(default=False)),
                ('tiene_manual_servicio', models.BooleanField(default=False)),
                ('tiene_guia_rapida', models.BooleanField(default=False)),
                ('tiene_registro_importacion', models.BooleanField(default=False)),
                ('tiene_carta_garantia', models.BooleanField(default=False)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='users.clinica')),
            ],
        ),
    ]
