# Generated by Django 5.2.4 on 2025-08-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipobiomedico',
            name='otros_datos_tecnicos',
        ),
        migrations.RemoveField(
            model_name='equipobiomedico',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='equipobiomedico',
            name='voltaje',
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='area_servicio',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='clasificacion_uso',
            field=models.CharField(choices=[('DIAGNOSTICO', 'Diagnóstico'), ('SOPORTE_VITAL', 'Soporte Vital'), ('LABORATORIO', 'Laboratorio Clínico'), ('TRATAMIENTO', 'Tratamiento/Quirúrgico'), ('TERAPEUTICO', 'Terapéutico/Rehabilitación'), ('ESTERILIZACION', 'Esterilización/Desinfección'), ('OTRO', 'Otro')], default='DIAGNOSTICO', max_length=50),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='corriente_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='frecuencia_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='fuente_combustion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='fuente_hidraulica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='fuente_neumatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='peso_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='potencia_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='precio_no_registra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='registro_sanitario_aplica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='temperatura_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='voltaje_vac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='voltaje_vac_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='voltaje_vdc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='voltaje_vdc_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='clasificacion_riesgo',
            field=models.CharField(blank=True, choices=[('I', 'Clase I'), ('IIA', 'Clase IIa'), ('IIB', 'Clase IIb'), ('III', 'Clase III')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='codigo_interno',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='corriente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='forma_adquisicion',
            field=models.CharField(choices=[('COMPRA_NUEVO', 'Compra (Nuevo)'), ('COMPRA_SEGUNDA', 'Compra (Segunda)'), ('DONACION', 'Donación'), ('COMODATO', 'Comodato'), ('OTRO', 'Otro')], default='COMPRA_NUEVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='frecuencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='garantia_anios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='potencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='proveedor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='registro_sanitario',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='serie',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='tecnologia_predominante',
            field=models.CharField(choices=[('MECANICO', 'Mecánico'), ('ELECTRICO', 'Eléctrico'), ('ELECTRONICO', 'Electrónico'), ('HIDRAULICO', 'Hidráulico'), ('NEUMATICO', 'Neumático'), ('INFORMATICO', 'Informático')], default='ELECTRONICO', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ParametroEntregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(choices=[('RPM', 'RPM'), ('TEMPERATURA', 'Temperatura (°C)'), ('PRESION', 'Presión (PSI)'), ('FLUJO', 'Flujo (lpm)'), ('PESO', 'Peso (kg)'), ('SPO2', 'Saturación de Oxígeno (SpO2)'), ('FC', 'Frecuencia Cardíaca (LPM)'), ('ENERGIA', 'Energía (J)')], max_length=50)),
                ('rango_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rango_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='inventory.equipobiomedico')),
            ],
        ),
    ]
