# Generated by Django 5.2.4 on 2025-08-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_equipobiomedico_otros_datos_tecnicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipobiomedico',
            name='hoja_vida_id',
            field=models.CharField(blank=True, help_text='ID único de la hoja de vida, generado automáticamente.', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='Indica si la hoja de vida tiene todos los datos críticos.'),
        ),
    ]
