# Generated by Django 5.2.4 on 2025-08-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipobiomedico_hoja_vida_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipobiomedico',
            name='ubicacion',
            field=models.CharField(default='No especificada', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='hoja_vida_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
