# Generated by Django 5.2.4 on 2025-08-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_equipobiomedico_hoja_vida_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipobiomedico',
            name='hoja_vida_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='ubicacion',
            field=models.CharField(default='No especificada', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='area_servicio',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='clasificacion_riesgo',
            field=models.CharField(blank=True, choices=[('I', 'Clase I'), ('IIA', 'Clase IIa'), ('IIB', 'Clase IIb'), ('III', 'Clase III')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='clasificacion_uso',
            field=models.CharField(choices=[('DIAGNOSTICO', 'Diagnóstico'), ('SOPORTE_VITAL', 'Soporte Vital'), ('LABORATORIO', 'Laboratorio Clínico'), ('TRATAMIENTO', 'Tratamiento/Quirúrgico'), ('TERAPEUTICO', 'Terapéutico/Rehabilitación'), ('ESTERILIZACION', 'Esterilización/Desinfección'), ('OTRO', 'Otro')], default='DIAGNOSTICO', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='codigo_interno',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='forma_adquisicion',
            field=models.CharField(choices=[('COMPRA_NUEVO', 'Compra (Nuevo)'), ('COMPRA_SEGUNDA', 'Compra (Segunda)'), ('DONACION', 'Donación'), ('COMODATO', 'Comodato'), ('OTRO', 'Otro')], default='COMPRA_NUEVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='proveedor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='registro_sanitario',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='tecnologia_predominante',
            field=models.CharField(choices=[('MECANICO', 'Mecánico'), ('ELECTRICO', 'Eléctrico'), ('ELECTRONICO', 'Electrónico'), ('HIDRAULICO', 'Hidráulico'), ('NEUMATICO', 'Neumático'), ('INFORMATICO', 'Informático')], default='ELECTRONICO', max_length=50),
        ),
    ]
