# Generated by Django 5.2.4 on 2025-08-02 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_equipobiomedico_hoja_vida_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipobiomedico',
            name='tiene_carta_garantia',
        ),
        migrations.RemoveField(
            model_name='equipobiomedico',
            name='tiene_guia_rapida',
        ),
        migrations.RemoveField(
            model_name='equipobiomedico',
            name='tiene_manual_servicio',
        ),
        migrations.RemoveField(
            model_name='equipobiomedico',
            name='tiene_manual_usuario',
        ),
        migrations.RemoveField(
            model_name='equipobiomedico',
            name='tiene_registro_importacion',
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='clasificacion_riesgo',
            field=models.CharField(blank=True, choices=[('I', 'Clase I'), ('IIA', 'Clase IIa'), ('IIB', 'Clase IIb'), ('III', 'Clase III'), ('N/A', 'N/A')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='corriente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='frecuencia_calibracion_meses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='peso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='potencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='precio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='temperatura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='voltaje_vac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipobiomedico',
            name='voltaje_vdc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Manual de Usuario, Factura, Otro', max_length=255)),
                ('archivo', models.FileField(upload_to='documentos_equipos/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inventory.equipobiomedico')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('motivo_cambio', models.TextField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventory.equipobiomedico')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
