# Generated by Django 5.2.4 on 2025-08-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_equipobiomedico_tiene_carta_garantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipobiomedico',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
