# Generated by Django 5.2.4 on 2025-08-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_equipobiomedico_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipobiomedico',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
