# Generated by Django 5.2.4 on 2025-08-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_equipobiomedico_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipobiomedico',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
